const DummyQuestions = [
  {
    id: 1,
    page: 1,
    title: "광고가 너무 많아요. 가리기 같은거 있으면 안될까요?",
    contents: "광고가 너무 많아요. 가리기 같은거 있으면 안될까요?",
    now: "created_at(10/11/2018)",
  },
  {
    id: 2,
    page: 1,
    title: "서비스 너무 좋아요! 감사합니다.",
    contents: "서비스 너무 좋아요! 감사합니다.",
    now: "created_at(10/13/2018)",
  },
  {
    id: 3,
    page: 1,
    title: "광고가 가끔 나타났으면 좋겠습니다.",
    contents: "광고가 가끔 나타났으면 좋겠습니다.",
    now: "created_at(10/13/2018)",
  },
  {
    id: 4,
    page: 1,
    title: "글 내용을 다 보여줄 순 없나요?",
    contents: "글 내용을 다 보여줄 순 없나요?",
    now: "created_at(10/14/2018)",
  },
  {
    id: 5,
    page: 1,
    title: "무한스크롤 완전 구림.",
    contents: "무한스크롤 완전 구림.",
    now: "created_at(10/15/2018)",
  },
  {
    id: 6,
    page: 1,
    title: "다 좋은데 글 우측 위에 있는 숫자가 뭔가요?",
    contents: "다 좋은데 글 우측 위에 있는 숫자가 뭔가요?",
    now: "created_at(10/15/2018)",
  },
  {
    id: 7,
    page: 1,
    title: "검색을 추가할 생각은 없나요?",
    contents: "검색을 추가할 생각은 없나요?",
    now: "created_at(10/20/2018)",
  },
  {
    id: 8,
    page: 1,
    title: "10개씩 불러오는거 더 늘려주세요!",
    contents: "10개씩 불러오는거 더 늘려주세요!",
    now: "created_at(10/20/2018)",
  },
  {
    id: 9,
    page: 1,
    title: "잘 쓰고 있습니다!",
    contents: "잘 쓰고 있습니다!",
    now: "created_at(10/22/2018)",
  },
  {
    id: 10,
    page: 1,
    title: "좋은 서비스 감사합니다! 좋은 글들 보일 때마다 복사해서 저만의 위키를 만들고 있어요! 주변 친구들한테도 소개할게요!!",
    contents: "좋은 서비스 감사합니다! 좋은 글들 보일 때마다 복사해서 저만의 위키를 만들고 있어요! 주변 친구들한테도 소개할게요!!",
    now: "created_at(10/23/2018)",
  },
  {
    id: 11,
    page: 2,
    title: "필터가 안되는거 같아요!",
    contents: "필터가 안되는거 같아요!",
    now: "created_at(10/23/2018)",
  },
  {
    id: 12,
    page: 2,
    title: "전 내림차순으로 보는데 올때마다 누르는게 귀찮아요. 마지막 정렬은 저장되었으면 좋겠어요.",
    contents: "전 내림차순으로 보는데 올때마다 누르는게 귀찮아요. 마지막 정렬은 저장되었으면 좋겠어요.",
    now: "created_at(10/23/2018)",
  },
  {
    id: 13,
    page: 2,
    title: "이미지가 안나와요.",
    contents: "이미지가 안나와요.",
    now: "created_at(10/23/2018)",
  },
  {
    id: 14,
    page: 2,
    title: "익스플로러에서 레이아웃이 깨져요.",
    contents: "익스플로러에서 레이아웃이 깨져요.",
    now: "created_at(10/23/2018)",
  },
  {
    id: 15,
    page: 2,
    title: "필터 걸면 순서가 이상해요.",
    contents: "필터 걸면 순서가 이상해요.",
    now: "created_at(10/23/2018)",
  },
  {
    id: 16,
    title: "필터 저장되었으면 좋겠어요.",
    contents: "필터 저장되었으면 좋겠어요.",
    now: "created_at(10/23/2018)",
  },
  {
    id: 17,
    page: 2,
    title: "이메일과 작성일이 밑에 나왔으면 좋겠어요.",
    contents: "이메일과 작성일이 밑에 나왔으면 좋겠어요.",
    now: "created_at(10/23/2018)",
  },
  {
    id: 18,
    page: 2,
    title: "drag 되는거 좀 막아주세요. 제 글이 유출될까봐 코멘토를 쓰기가 두렵네요.",
    contents: "drag 되는거 좀 막아주세요. 제 글이 유출될까봐 코멘토를 쓰기가 두렵네요.",
    now: "created_at(10/27/2018)",
  },
  {
    id: 19,
    page: 2,
    title: "필터값 저장되면 좋겠어요.",
    contents: "필터값 저장되면 좋겠어요.",
    now: "created_at(10/27/2018)",
  },
  {
    id: 20,
    page: 2,
    title: "이거 뭐지?",
    contents: "이거 뭐지?",
    now: "created_at(10/28/2018)",
  },
  {
    id: 21,
    page: 3,
    title: "감사하다고 말하고 싶었어요. 히히",
    contents: "감사하다고 말하고 싶었어요. 히히",
    now: "created_at(10/28/2018)",
  },
  {
    id: 22,
    page: 3,
    title: "로딩이미지 같은거 없나요? 에러 같아요.",
    contents: "로딩이미지 같은거 없나요? 에러 같아요.",
    now: "created_at(10/28/2018)",
  },
  {
    id: 23,
    page: 3,
    title: "페북처럼 스크롤만 내리면 콘텐츠가 계속 나오니까 좋네요.",
    contents: "페북처럼 스크롤만 내리면 콘텐츠가 계속 나오니까 좋네요.",
    now: "created_at(10/29/2018)",
  },
  {
    id: 24,
    page: 3,
    title: "엄청 느리네",
    contents: "엄청 느리네",
    now: "created_at(10/30/2018)",
  },
  {
    id: 25,
    page: 3,
    title: "검색이 필요하다!",
    contents: "검색이 필요하다!",
    now: "created_at(10/31/2018)",
  },
  {
    id: 26,
    page: 3,
    title: "네이버는 리스트 더 보기 버튼으로 되어 있던데 그게 더 편한듯",
    contents: "네이버는 리스트 더 보기 버튼으로 되어 있던데 그게 더 편한듯",
    now: "created_at(10/31/2018)",
  },
    {
    id: 27,
    page: 3,
    title: "필터 하면 내가 뭐했는지 보였으면 좋겠어요.",
    contents: "필터 하면 내가 뭐했는지 보였으면 좋겠어요.",
    now: "created_at(10/31/2018)",
  },
  {
    id: 28,
    page: 3,
    title: "글 내용 한 줄은 너무 적은거 같은데 더 나오게 할 생각은 없어요?",
    contents: "글 내용 한 줄은 너무 적은거 같은데 더 나오게 할 생각은 없어요?",
    now: "created_at(11/01/2018)",
  },
  {
    id: 29,
    page: 3,
    title: "이메일이 맨위에 있으니까 작성하신 분이 누군지 잘보여서 너무 좋아요! cs* 멘토님 정말 친절하시고 짱입니다!!!",
    contents: "이메일이 맨위에 있으니까 작성하신 분이 누군지 잘보여서 너무 좋아요! cs* 멘토님 정말 친절하시고 짱입니다!!!",
    now: "created_at(11/01/2018)",
  },
  {
    id: 30,
    page: 3,
    title: "광고는 뭐냐 광고 없애라ㅡㅡ",
    contents: "광고는 뭐냐 광고 없애라ㅡㅡ",
    now: "created_at(11/08/2018)",
  },
]

export default DummyQuestions;